### ISSUE TITLE
Spaces should be allowed in /loc save

### ISSUE THREAD

**Issue by ifvictr** [ifvictr/HCCore#63]
Currently, it just saves the second parameter instead of combining everything after the first. This won't cause a problem with the JSON keys.

**Comment by wei2gao** [comment]
I'm taking a look at this

**Comment by wei2gao** [comment]
I've discovered that if I type, say, "/loc save foo      bar", then the location saved is "foo bar" because I don't think the way of getting the args list in onCommand preserves whitespace at all. Is there any way to get around this?

**Comment by ifvictr** [comment]
@wei2gao You need to join all the args after `save`. We do something like. this here: https://github.com/ifvictr/HCCore/blob/a18bf6ce0837b52367ab9e994c3456595b5dec55/src/main/java/com/hackclub/hccore/commands/ShrugCommand.java#L30

**Comment by wei2gao** [comment]
Looks like the spaces didn't show up right in the comment. What I meant is that if I type lots of spaces between words, then join ends up replacing it with one space because I'm not sure if there's a way to preserve the original whitespace.

**Comment by ifvictr** [comment]
Yeah, that's intentional behavior on Minecraft's part. Don't think there's anything you can do about it. We don't really care about how many whitespaces there is as long as there's one between each word.
